name: tizonia
version: 0.22.0
summary: Tizonia command-line cloud music player.
description: |
  Command-line cloud music player for Linux with support for Spotify,
  Google Play Music, YouTube, SoundCloud, TuneIn, iHeartRadio, Plex
  and Chromecast.
grade: stable
confinement: strict
base: core18
architectures:
  - build-on: amd64
    run-on: amd64

  - build-on: i386
    run-on: i386

  - build-on: armhf
    run-on: armhf

slots:
  tizrmd-slot: # Tizonia's OpenMAX IL resource management daemon
    interface: dbus
    bus: session
    name: com.aratelia.tiz.tizrmd
  tizcastd-slot: # Tizonia's Chromecast access daemon
    interface: dbus
    bus: session
    name: com.aratelia.tiz.tizcastd

plugs:
  tizrmd-plug: # Tizonia's OpenMAX IL resource management daemon
    interface: dbus
    bus: session
    name: com.aratelia.tiz.tizrmd
  tizcastd-plug: # Tizonia's Chromecast access daemon
    interface: dbus
    bus: session
    name: com.aratelia.tiz.tizcastd

apps:
  tizrmd:
    command: usr/bin/tizrmd
    slots:
      - tizrmd-slot

  tizcastd:
    command: usr/bin/tizcastd
    slots:
      - tizcastd-slot

  tizonia:
    desktop: usr/share/applications/tizonia.desktop
    command: bin/snapcraft-preload $SNAP/bin/tizonia-snap-wrapper.sh
    completer: usr/share/bash-completion/completions/tizonia
    plugs:
      - home
      - network
      - network-bind
      - audio-playback
      - process-control
      - alsa
      - removable-media
      - mount-observe
      - network-control
      - x11
      - tizrmd-plug
      - tizcastd-plug
    slots:
      - mpris

parts:
  # Semaphore-support (Python multitasking)
  snapcraft-preload:
    source: https://github.com/diddledan/snapcraft-preload.git
    source-branch: semaphore-support
    plugin: cmake
    build-packages:
      - on amd64:
          - gcc-multilib
          - g++-multilib
    stage-packages:
      - on amd64 to amd64:
        - lib32stdc++6
  pypideps:
    plugin: python
    python-version: python3
    build-packages:
      - python3-all-dev
      - libxml2-dev
      - libxslt1-dev
    python-packages:
      - gmusicapi
      - soundcloud
      - youtube-dl
      - pafy
      - pycountry
      - titlecase
      - pychromecast
      - plexapi
      - fuzzywuzzy
      - eventlet
      - python-Levenshtein
      - joblib
    filesets:
      no-need-stuff:
        - -include/
        - -var/
        - -share/
        - -usr/share
        - -snap/
    stage:
      - $no-need-stuff
    prime:
      - $no-need-stuff

  spotipy:
    plugin: python
    python-version: python3
    source-type: git
    source: https://github.com/plamere/spotipy
    filesets:
      no-need-stuff:
        - -bin/chardetect
        - -include/
        - -var/
        - -share/
        - -usr/share
        - -snap/
    stage:
      - $no-need-stuff
    prime:
      - $no-need-stuff
    after:
      - pypideps

  tizonia:
    plugin: meson
    source: https://github.com/tizonia/tizonia-openmax-il.git
    source-commit: 208aa1483d2348e8ef528fb746341cf469b01862
    override-build: |
      env
      # NOTE: The check for Mopidy's apt archive presence in sources.list is disabled,
      # since it fails when building with 'snapcraft cleanbuild'.
      # Re-enable when building without cleanbuild to avoid adding the apt archive
      # multiple times to sources.list.
      #
      # Add Mopidy's archive to APT's sources.list
      # grep -q "apt.mopidy.com" /etc/apt/sources.list
      # if [ "$?" -eq 1 ]; then
      curl 'http://apt.mopidy.com/mopidy.gpg' | apt-key add -
      curl https://apt.mopidy.com/stretch.list -o /etc/apt/sources.list.d/mopidy.list
      # fi
      apt-get update && apt-get -y install libspotify-dev
      pip3 uninstall --yes meson && pip3 install meson==0.53.0
      meson . build --buildtype=release --prefix=$SNAPCRAFT_PART_INSTALL/usr --sysconfdir=$SNAPCRAFT_PART_INSTALL/etc --localstatedir=$SNAPCRAFT_PART_INSTALL/var --sharedstatedir=$SNAPCRAFT_PART_INSTALL/var/lib
      ninja -j1 -C build
      ninja -C build install
      perl -i -p -e 's|^component-paths.*|component-paths = \$TIZONIA_PLUGINS_DIR|' $SNAPCRAFT_PART_INSTALL/etc/xdg/tizonia/tizonia.conf
      perl -i -p -e 's|^rmdb.*|rmdb = \$TIZONIA_PLUGINS_DIR/usr/share/tizrmd/tizrm.db|' $SNAPCRAFT_PART_INSTALL/etc/xdg/tizonia/tizonia.conf
      perl -i -p -e 's|^Icon=tizonia|Icon=/usr/share/icons/hicolor/256x256/apps/tizonia\.png|' $SNAPCRAFT_PART_INSTALL/usr/share/applications/tizonia.desktop
      perl -i -p -e 's|^Exec.*|Exec=/usr/bin/tizcastd|' $SNAPCRAFT_PART_INSTALL/usr/share/dbus-1/services/com.aratelia.tiz.cast.service
      perl -i -p -e 's|^Exec.*|Exec=/usr/bin/tizrmd|' $SNAPCRAFT_PART_INSTALL/usr/share/dbus-1/services/com.aratelia.tiz.rm.service
    build-packages:
      - build-essential
      - cmake
      - libtool
      - dpkg-dev
      - libmad0-dev
      - liblog4c-dev
      - libasound2-dev
      - libdbus-1-dev
      - libsqlite3-dev
      - libboost-system-dev
      - libboost-python-dev
      - libboost-filesystem-dev
      - libboost-thread-dev
      - libboost-program-options-dev
      - uuid-dev
      - libsdl1.2-dev
      - libvpx-dev
      - libmp3lame-dev
      - libfaad-dev
      - libtag1-dev
      - libfishsound1-dev
      - libmediainfo-dev
      - libcurl4-gnutls-dev
      - libpulse-dev
      - libmpg123-dev
      - libvorbis-dev
      - libopus-dev
      - libopusfile-dev
      - libogg-dev
      - libflac-dev
      - liboggz2-dev
      - libsndfile1-dev
      - libffi-dev
      - libssl-dev
      - libexpat1-dev
      - python3-dev
      - python3-all-dev
      - python3-setuptools
      - python3-pip
      - check
      - sqlite3
      - dbus-x11
      - curl
      - execstack
    stage-packages:
      - libmad0
      - liblog4c3
      - libasound2
      - libpulse0
      - libdbus-1-3
      - libsqlite3-0
      - libboost-system1.65.1
      - libboost-python1.65.1
      - libboost-filesystem1.65.1
      - libboost-thread1.65.1
      - libboost-program-options1.65.1
      - uuid-runtime
      - libsdl1.2debian
      - libvpx5
      - libmp3lame0
      - libfaad2
      - libtag1v5
      - libfishsound1
      - libmediainfo0v5
      - libmpg123-0
      - libvorbis0a
      - libopus0
      - libopusfile0
      - libogg0
      - libflac8
      - liboggz2
      - libsndfile1
      - libcurl4
      - libffi6
      - libpython3.6
      - libslang2
      - libgl1
      - libglu1-mesa
      - libglvnd0
      - libglx0
      - sqlite3
      - dbus-x11
      - freeglut3
      - libasn1-8-heimdal
      - libasyncns0
      - libcaca0
      - libgssapi3-heimdal
      - libhcrypto4-heimdal
      - libheimbase1-heimdal
      - libheimntlm0-heimdal
      - libhx509-5-heimdal
      - libicu60
      - libkrb5-26-heimdal
      - libldap-2.4-2
      - libmms0
      - libpsl5
      - libroken18-heimdal
      - librtmp1
      - libsasl2-2
      - libspeex1
      - libtag1v5-vanilla
      - libtinyxml2-6
      - libvorbisenc2
      - libwind0-heimdal
      - libx11-6
      - libxau6
      - libxcb1
      - libxdmcp6
      - libxext6
      - libzen0v5
    after:
      - spotipy
    organize:
      usr/lib/python3.6/site-packages: lib/python3.6/site-packages
    filesets:
      no-need-stuff:
        - -include/
        - -var/
        - -snap/
        - "-usr/lib/*/cmake/*"
        - "-usr/include/*"
        - "-usr/share/ECM/*"
        - "-usr/share/doc/*"
        - "-usr/share/man/*"
        - "-usr/bin/X11"
        - "-usr/lib/gcc/x86_64-linux-gnu/6.0.0"
        - "-usr/lib/aspell/*"
    stage:
      - $no-need-stuff
    prime:
      - $no-need-stuff

  env:
    plugin: nil
    override-build: |
      find / ! -readable -prune -o -type f -name "libspotify.so.*" -exec ls {} \; -exec execstack --clear-execstack {} \; || true
    stage-packages:
      - libspotify12
    after:
      - tizonia

  wrapper:
    plugin: dump
    source: wrapper
    organize:
      tizonia-snap-wrapper.sh: bin/tizonia-snap-wrapper.sh
    after:
      - env
