name: tizonia
version: 0.15.0
summary: Tizonia command-line cloud music player.
description: |
  Command-line cloud music player for Linux with support for Spotify,
  Google Play Music, YouTube, SoundCloud, Dirble, Plex and Chromecast.
grade: stable
confinement: strict

slots:
  tizrmd-slot: # Tizonia's OpenMAX IL resource management daemon
    interface: dbus
    bus: session
    name: com.aratelia.tiz.tizrmd
  tizcastd-slot: # Tizonia's Chromecast access daemon
    interface: dbus
    bus: session
    name: com.aratelia.tiz.tizcastd

plugs:
  tizrmd-plug: # Tizonia's OpenMAX IL resource management daemon
    interface: dbus
    bus: session
    name: com.aratelia.tiz.tizrmd
  tizcastd-plug: # Tizonia's Chromecast access daemon
    interface: dbus
    bus: session
    name: com.aratelia.tiz.tizcastd

apps:
  tizrmd:
    command: usr/bin/tizrmd
    slots:
      - tizrmd-slot

  tizcastd:
    command: usr/bin/tizcastd
    slots:
      - tizcastd-slot

  tizonia:
    desktop: usr/share/applications/tizonia.desktop
    command: bin/tizonia-snap-wrapper.sh
    plugs:
      - home
      - network
      - network-bind
      - pulseaudio
      - process-control
      - alsa
      - removable-media
      - x11
      - tizrmd-plug
      - tizcastd-plug
    slots:
      - mpris

parts:
  pypideps:
    plugin: python
    python-version: python2
    build-packages:
      - python-dev
      - libxml2-dev
      - libxslt1-dev
    python-packages:
      - soundcloud
      - gmusicapi
      - youtube-dl
      - pafy
      - pycountry
      - titlecase
      - pychromecast
      - plexapi
      - fuzzywuzzy
      - python-Levenshtein
      - eventlet
    filesets:
      no-need-stuff:
        - -include/
        - -var/
        - -share/
        - -usr/share
        - -snap/
    stage:
      - $no-need-stuff
    prime:
      - $no-need-stuff

  spotipy:
    plugin: python
    python-version: python2
    source-type: git
    source: https://github.com/plamere/spotipy
    filesets:
      no-need-stuff:
        - -bin/chardetect
        - -include/
        - -var/
        - -share/
        - -usr/share
        - -snap/
    stage:
      - $no-need-stuff
    prime:
      - $no-need-stuff
    after:
      - pypideps

  tizonia:
    plugin: autotools
    source: https://github.com/tizonia/tizonia-openmax-il.git
    # source-tag: 0.13.0
    override-build: |
      # NOTE: The check for Mopidy's apt archive presence in sources.list is disabled,
      # since it fails when building with 'snapcraft cleanbuild'.
      # Re-enable when building without cleanbuild to avoid adding the apt archive
      # multiple times to sources.list.
      #
      # Add Mopidy's archive to APT's sources.list
      # grep -q "apt.mopidy.com" /etc/apt/sources.list
      # if [ "$?" -eq 1 ]; then
      curl 'http://apt.mopidy.com/mopidy.gpg' | apt-key add -
      echo "deb http://apt.mopidy.com/ stable main contrib non-free" | tee -a /etc/apt/sources.list
      # fi
      apt-get update && apt-get -y install libspotify-dev
      autoreconf -ifsv 2>&1 | grep --color=always '.*Entering directory'
      ./configure --prefix=$SNAPCRAFT_PART_INSTALL/usr --sysconfdir=$SNAPCRAFT_PART_INSTALL/etc --with-boost-libdir=/usr/lib/$(dpkg-architecture -qDEB_HOST_MULTIARCH) --without-bashcompletiondir --without-zshcompletiondir --enable-silent-rules CFLAGS='-O2 -s -DNDEBUG' CXXFLAGS='-O2 -s -DNDEBUG -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security' || cat player/config.log
      make -j1 V=0
      make install
      perl -i -p -e 's|^component-paths.*|component-paths = \$TIZONIA_PLUGINS_DIR|' $SNAPCRAFT_PART_INSTALL/etc/xdg/tizonia/tizonia.conf
      perl -i -p -e 's|^rmdb.*|rmdb = \$TIZONIA_PLUGINS_DIR/usr/share/tizrmd/tizrm.db|' $SNAPCRAFT_PART_INSTALL/etc/xdg/tizonia/tizonia.conf
      perl -i -p -e 's|^Icon=tizonia|Icon=/usr/share/icons/hicolor/256x256/apps/tizonia\.png|' $SNAPCRAFT_PART_INSTALL/usr/share/applications/tizonia.desktop
      perl -i -p -e 's|^Exec.*|Exec=/usr/bin/tizcastd|' $SNAPCRAFT_PART_INSTALL/usr/share/dbus-1/services/com.aratelia.tiz.cast.service
      perl -i -p -e 's|^Exec.*|Exec=/usr/bin/tizrmd|' $SNAPCRAFT_PART_INSTALL/usr/share/dbus-1/services/com.aratelia.tiz.rm.service
    build-packages:
      - build-essential
      - autoconf
      - autoconf-archive
      - automake
      - autotools-dev
      - libtool
      - dpkg-dev
      - libmad0-dev
      - liblog4c-dev
      - libasound2-dev
      - libdbus-1-dev
      - libsqlite3-dev
      - libboost-system-dev
      - libboost-python-dev
      - libboost-filesystem-dev
      - libboost-thread-dev
      - libboost-program-options-dev
      - uuid-dev
      - libsdl1.2-dev
      - libvpx-dev
      - libmp3lame-dev
      - libfaad-dev
      - libtag1-dev
      - libfishsound1-dev
      - libmediainfo-dev
      - libcurl4-gnutls-dev
      - libpulse-dev
      - libmpg123-dev
      - libvorbis-dev
      - libopus-dev
      - libopusfile-dev
      - libogg-dev
      - libflac-dev
      - liboggz2-dev
      - libsndfile1-dev
      - libffi-dev
      - libssl-dev
      - libexpat1-dev
      - python-dev
      - python-setuptools
      - python-pip
      - python-decorator
      - python-protobuf
      - python-validictory
      - python-bs4
      - python-oauth2client
      - python-dateutil
      - python-mutagen
      - python-crypto
      - python-requests
      - check
      - sqlite3
      - dbus-x11
      - curl
      - execstack
    after:
      - spotipy
    organize:
      usr/lib/python2.7/site-packages: lib/python2.7/site-packages
    filesets:
      no-need-stuff:
        - -include/
        - -var/
        - -snap/
    stage:
      - $no-need-stuff
    prime:
      - $no-need-stuff

  env:
    plugin: nil
    override-build: |
      find / ! -readable -prune -o -type f -name "libspotify.so.*" -exec ls {} \; -exec execstack --clear-execstack {} \; || true
    stage-packages:
      - libmad0
      - liblog4c3
      - libasound2
      - libpulse0
      - libdbus-1-3
      - libsqlite3-0
      - libboost-system1.58.0
      - libboost-python1.58.0
      - libboost-filesystem1.58.0
      - libboost-thread1.58.0
      - libboost-program-options1.58.0
      - uuid-runtime
      - libsdl1.2debian
      - libvpx3
      - libmp3lame0
      - libfaad2
      - libtag1v5
      - libfishsound1
      - libmediainfo0v5
      - libmpg123-0
      - libvorbis0a
      - libopus0
      - libopusfile0
      - libogg0
      - libflac8
      - liboggz2
      - libsndfile1
      - libspotify12
      - libcurl3
      - libffi6
      - sqlite3
      - dbus-x11
    filesets:
      no-need-stuff:
        - -include/
        - -var/
        - -snap/
      no-usr-lib-python2-dot-7:
        - -usr/bin/2to3-2.7
        - -usr/bin/pydoc2.7
        - -usr/lib/python2.7/UserString.py
        - -usr/lib/python2.7/base64.py
        - -usr/lib/python2.7/cProfile.py
        - -usr/lib/python2.7/cgi.py
        - -usr/lib/python2.7/encodings/rot_13.py
        - -usr/lib/python2.7/ensurepip/__init__.py
        - -usr/lib/python2.7/keyword.py
        - -usr/lib/python2.7/lib2to3/pgen2/token.py
        - -usr/lib/python2.7/mimify.py
        - -usr/lib/python2.7/pdb.py
        - -usr/lib/python2.7/platform.py
        - -usr/lib/python2.7/profile.py
        - -usr/lib/python2.7/pydoc.py
        - -usr/lib/python2.7/quopri.py
        - -usr/lib/python2.7/sitecustomize.py
        - -usr/lib/python2.7/smtpd.py
        - -usr/lib/python2.7/smtplib.py
        - -usr/lib/python2.7/symbol.py
        - -usr/lib/python2.7/tabnanny.py
        - -usr/lib/python2.7/test/pystone.py
        - -usr/lib/python2.7/test/regrtest.py
        - -usr/lib/python2.7/timeit.py
        - -usr/lib/python2.7/trace.py
        - -usr/lib/python2.7/uu.py
        - -usr/lib/python2.7/webbrowser.py
        - -usr/share/python/dh_python2
        - -usr/share/python/pyversions.py
    stage:
      - $no-need-stuff
      - $no-usr-lib-python2-dot-7
    prime:
      - $no-need-stuff
      - $no-usr-lib-python2-dot-7
    after:
      - tizonia

  wrapper:
    plugin: dump
    source: wrapper
    organize:
      tizonia-snap-wrapper.sh: bin/tizonia-snap-wrapper.sh
    after:
      - env
